name:                pass
version:             0.1.0.0
github:              "githubuser/pass"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pass#readme>

dependencies:
- base >= 4.7 && < 5
- directory >= 1.3.6.2
- split >= 0.2.3.4

library:
  source-dirs: src

executables:
  pass-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pass

tests:
  pass-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -qg"'
    dependencies:
    - pass
    - hspec >=2.0.0
    - hspec-expectations-lifted
